import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "./header";
import Footer from "./footer";
const roboto = Roboto({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "700"],
});
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata: Metadata = {
  title: "tailwindcss App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
